workflows:
  my-workflow:                # workflow ID
    name: Workflow TriangleApp    # workflow name displayed in Codemagic UI
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "TriangleApp.xcodeproj" # Isikan nama project Anda.
          XCODE_SCHEME: "TriangleApp" # Isikan nama scheme project Anda.
    scripts:
        - name: Run tests
          script: |
            xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.4' \
            clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        - name: Build debug app
          script: |
            xcodebuild build -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
          recipients:
            - agungdwisaputra0808@gmail.com # Isikan email untuk notifikasi status building.
